### ISSUE TITLE
Redundancy

### ISSUE THREAD

**Issue by khaledkee** [Ahmed-YehiaGPEL/Polynomial-Calculator#15]
There are many _redundancies_ in the code base. For example, in [PolynomialTrie](https://github.com/Ahmed-YehiaGPEL/Polynomial-Calculator/blob/master/PolynomialTree/Trie.cs), [dfs and dfsSecond](https://github.com/Ahmed-YehiaGPEL/Polynomial-Calculator/blob/master/PolynomialTree/Trie.cs#L384) are pretty much **the same**. In [MainForm.cs](https://github.com/Ahmed-YehiaGPEL/Polynomial-Calculator/blob/master/CalculatorUI/MainForm.cs), [LogInHistory](https://github.com/Ahmed-YehiaGPEL/Polynomial-Calculator/blob/master/CalculatorUI/MainForm.cs#L158) call [LogItem](https://github.com/Ahmed-YehiaGPEL/Polynomial-Calculator/blob/master/CalculatorUI/MainForm.cs#L194) in every _case_ of the _switch_ with the **same parameter**.

**Comment by sallam-ahmed** [comment]
_Will enhance [MainForm.cs](https://github.com/Ahmed-YehiaGPEL/Polynomial-Calculator/blob/master/CalculatorUI/MainForm.cs) after finishing parsing algorithm._
