### ISSUE TITLE
Coefficient 1 Input Bug

### ISSUE THREAD

**Issue by sallam-ahmed** [Ahmed-YehiaGPEL/Polynomial-Calculator#17]
If the input coefficient is NULL hence meaning 1:
_1x^2_ == _x^2_

if _x_ is written in lower case bug arises:
![image](https://cloud.githubusercontent.com/assets/10068638/11998285/3878f536-aaa0-11e5-8936-fa8241d33c6f.png)

if _X_ in uppercase it's parsed:
![image](https://cloud.githubusercontent.com/assets/10068638/11998288/4a15fc26-aaa0-11e5-93ae-7be5bf12024e.png)

**Comment by khaledkee** [comment]
I think this is the problem, [MainForm.cs line 517-516](https://github.com/Ahmed-YehiaGPEL/Polynomial-Calculator/blob/master/CalculatorUI/MainForm.cs#L517):

``` cs
if (expr.StartsWith("X"))
                expr = "1" + expr;
```

There is no similar condition for the lower case. Also see line [514](https://github.com/Ahmed-YehiaGPEL/Polynomial-Calculator/blob/master/CalculatorUI/MainForm.cs#L517) and [515](https://github.com/Ahmed-YehiaGPEL/Polynomial-Calculator/blob/master/CalculatorUI/MainForm.cs#L515).
