### ISSUE TITLE
Multiplication bug- zero coefficient

### ISSUE THREAD

**Issue by sallam-ahmed** [Ahmed-YehiaGPEL/Polynomial-Calculator#21]
When multiplying 2 polynomials that results in a zero coefficient term it's added to the result.
_check the image_
![image](https://cloud.githubusercontent.com/assets/10068638/12004600/de7c477a-ab6e-11e5-8052-efe13e9030e8.png)

**_I think it should be edited from the polynomial operators section:_** [Polynomial.cs](https://github.com/Ahmed-YehiaGPEL/Polynomial-Calculator/blob/master/Polynomial/Polynomial.cs#L230)

**Comment by khaledkee** [comment]
I did try to produce this bug, but I was too dumb to find such simple case. So I assumed it won't happen.

> Crashes, corruption, and glitches usually happen because somebody assumed something wouldn’t fail.
> [Source](http://mortoray.com/2015/11/06/everything-can-and-will-go-wrong-all-functions-fail)
