### ISSUE TITLE
Multiple bugs

### ISSUE THREAD

**Issue by sallam-ahmed** [Ahmed-YehiaGPEL/Polynomial-Calculator#23]
**Multiple bugs aroused while testing:**
- When multiplying _x_ by _1_, the result is stored with a conflict in history
  _Check the image_
  ![image](https://cloud.githubusercontent.com/assets/10068638/12006759/7e4b3c16-abec-11e5-8dbf-6f798b974312.png)
- When dividing _x_ by _1_, the result is 1 and stored with the same conflict in history:
  _Check the image_
  ![image](https://cloud.githubusercontent.com/assets/10068638/12006766/c3d45af6-abec-11e5-93a2-46b4a9402a5a.png)
  **_When dividing _1_ by _x_ the result is zero.**
- When multiplying _1_ by _x_, **_I expected the same result as point 1 but it's not_**, the parser parses _1_ in the first polynomial as _x_ and outputs _x^2_:
  _Check the image_
  ![image](https://cloud.githubusercontent.com/assets/10068638/12006778/2bdae656-abed-11e5-80ed-4d8ed7078713.png)
- When subtracting _x_ from _1_ it shouldn't output _-1x_ it should output _x_ only, as fixed before but obviously it wasn't handled.
  _Check the image_
  ![image](https://cloud.githubusercontent.com/assets/10068638/12006787/b905f41c-abed-11e5-8683-c65d1bc23a2f.png)

**_That's it for now_**

**Comment by khaledkee** [comment]
I'm very sorry for this silly bug. I used minimum_rank1 instead of minimum_rank2 in [line250](https://github.com/Ahmed-YehiaGPEL/Polynomial-Calculator/blob/master/Polynomial/Polynomial.cs#L250). I solved the subtraction bug also. I'm still fixing the history one.

**Comment by khaledkee** [comment]
About the division one, I can't reproduce this bug. Maybe it was unintentionally solved in the last pull request.

**Comment by sallam-ahmed** [comment]
@khaledkee  it's ok, did you fix the whole bugs in the last pull request ? #22 _Bug fixes_

**Comment by khaledkee** [comment]
~~Yes.~~
Note: I couldn't reproduce the division bug. Could you provide a complete log for the bug?!
Unfortunately, I didn't save any unit test. If I had saved all unit test, we could have easily run them before each commit to ensure that every single function behaves correctly.
I'll try to re-write all unit tests before tomorrow. In the meantime, please test the code exhaustively.

**Comment by sallam-ahmed** [comment]
I'll test the code until you get the unit tests ready, I'll merge the last pull request then try to reproduce the division bug again.
