### ISSUE TITLE
History log loading, open-with command

### ISSUE THREAD

**Issue by sallam-ahmed** [Ahmed-YehiaGPEL/Polynomial-Calculator#31]
### Phase 4 work

Enables user to use a set of operations stored in a operations database ( history log ) through an open-with shell command, so that the application may use the desired database to read / write on.

Enable the user to save the current operations database as an external file for later loading.

_operations database is not an **_xml**_ file it's a specific extension for the app._

**Comment by khaledkee** [comment]
I think that some users may mess around with the extension. However, some programs (for example, Classic Media Player) can open a file with wrong extension, provided that the file header (first 3 or so bytes) is correct. XWRT uses a 4-byte file header. On the other hand, that doesn't guarantee that the input is correct. My question here is: Should I restrict the _load from file_ option to only plcl (or any other extension we may think of for our program) files, or to XWRT file header?!

**Comment by sallam-ahmed** [comment]
If the users messed up with the extension what would they do, hence they cannot read the data inside, aren't we ciphering them ?

**Comment by khaledkee** [comment]
~~I mean in the OpenFileDialog, should I restrict the input to our extension only or confirm the file header after the user chooses the file?!~~ forget about it, it's just working anyway!

**Comment by sallam-ahmed** [comment]
It should be restricted to the extension only.. not every file, and you should check too..

consider a user who made a file with the program’s extension it’d be opened but will fail for reading data, anyways you’ll need to check the header.
