### ISSUE TITLE
Log panel enhancement 

### ISSUE THREAD

**Issue by sallam-ahmed** [Ahmed-YehiaGPEL/Polynomial-Calculator#35]
What about removing the log panel and make the latest log message appear as a label in the  status bar

When double clicking on the last message in the bar, a new form appears that contains the log, like the _Unity 3D_ console.

**Comment by khaledkee** [comment]
- I expected something different! Why don't we load all past calculations from the trie in the ~~log~~ historyListBox?! What's more, when someone enter a past calculation, why doesn't it appear in the ~~log~~ historyListBox?! I mean, why don't we bring it to the end of the list and remove it from its previous position?! We can put a limit to ~~Log~~ historyListBox as well.
- I'd like to see a auto-completion menu for polynomials RichTextBoxes.

**Comment by sallam-ahmed** [comment]
It will be removed from its position anyways, but loading previous polys. from the Trie in it. What’s the point of that?

Also the log panel is meant to keep track on everything happens in the app. When someone enters a past calculation we show it in the result panel, let’s not make the user confused and look for the result in two places!

**Comment by khaledkee** [comment]
I mistakenly wrote log. I meant the historyListBox. Sorry for inconvenience. 
I agree on removing log and replacing it with the status bar.

**Comment by sallam-ahmed** [comment]
Oh, now that's clear.. we agree on replacing the current history loading style by loading all the previous polynomials in it, and build the polynomial explorer control that contains the following:
1. Polynomial in RTF
2. References to all operations done on it
3. Plotting graph of it.
when clicking on any polynomial the explorer will popup as a form extender in the right of the form showing the desired information.
