### ISSUE TITLE
Dfs redundancy

### ISSUE THREAD

**Issue by khaledkee** [Ahmed-YehiaGPEL/Polynomial-Calculator#38]
When we started the polynomial calculator, it was intended for _two polynomials operations_ with the only exception for _finding roots_ at the time. More _one polynomial operations_ has been introduced. If you opened the _dfs_ functions, you'll find that _dfs_ and _dfsSecond_ are very similar but the small difference they have doesn't allow merging them. Basically the difference is that _dfsSecond_ doesn't contain _one polynomial operations_. What's more, is that each _one polynomial operations_ are treated differently (each one has difference loop), however, any _two polynomial operation_ is considered the same. The reasons and details is omitted. I'm thinking of refactoring the dfs functions to be more generic and elegant.

**Comment by sallam-ahmed** [comment]
How would you manage to do that ? by eliminating one of the functions and using only one for bot ?!
Both are treated differently, the one way would be considering the one polynomial operation is virtually **two operations** , would it be like that ?!
P.S : 
I support redundancy fixing, the lesser the better [**_considering same performance and reliability_**]

**Comment by khaledkee** [comment]
> Both are treated differently, the one way would be considering the one polynomial operation is virtually two operations , would it be like that ?!

No.

> How would you manage to do that ?

First to successfully merge the two functions, we should change the character for _root finding_. The result of _two polynomials operation_ is stored with link '=' the same as _root finding_. Then, there is essentially two types of _one polynomial operations_ those with parameters and those without. The biggest difference is that with parameters you can have different results for different parameters, and these results are stored in dictionary along with the parameters (as Key). That's what makes storing derivative differs from storing substitution for example. The problem here is that dictionary doesn't contain ToString(), or precisely it doesn't behave as we want. So we wrote a small loop to convert it. But as you can see, there is a condition for each special link to determine if it's dictionary or not. On the bright side, we can just write a function that takes the _specially linked objects_ and determine how to convert them to String or _XML Element_. Then call it for any _special link_ in the dfs including the result of _two polynomial operations_ which is a polynomial and it DOES contain ToString() that behaves as we want.
