### ISSUE TITLE
PolynomialSolver Constructor

### ISSUE THREAD

**Issue by sallam-ahmed** [Ahmed-YehiaGPEL/Polynomial-Calculator#7]
The constructor takes a double array of coefficients

Enhance it to take PolynomialClass instead then extract the coeffs. out of it .

**Comment by khaledkee** [comment]
PolynomialSolver has a constructor that takes a Polynomial class, it's just set to private, see lines 31-37:

``` cpp
private Solver(Polynomial p)
{
    Complex[] _cn = new Complex[p.Count];
    for (int i = 0; i < p.Count; i++)
        _cn[i] = p[i].Coefficient;
    cof = _cn;
}
```

**Comment by sallam-ahmed** [comment]
I'll make it public then.
