### ISSUE TITLE
Multiplication Bug

### ISSUE THREAD

**Issue by sallam-ahmed** [Ahmed-YehiaGPEL/Polynomial-Calculator#8]
Assume multiplying 
**(x+4) and (x+4)**
the result would be 
**x^2 + 8x + 16** 
Current output :
**8x+ 17** 

**Function calling**

``` C#
polynomial1 = GetPolynomial(flowPolynomial1.Controls);
polynomial2 = GetPolynomial(flowPolynomial2.Controls);
resultPolynomial = polynomial1 * polynomial2;
```

_Polynomials are stored successfully and result polynomial isn't calculated correctly_

**Comment by khaledkee** [comment]
That's _weird_. I used TestApp class (the same code on the repo) and it outputs the right answer.
![NoBug](https://cloud.githubusercontent.com/assets/5068410/11763036/9465e026-a103-11e5-86f8-31bc378dc847.png)

**Comment by sallam-ahmed** [comment]
![image](https://cloud.githubusercontent.com/assets/10068638/11763773/de8fc452-a11f-11e5-9027-00339d0d1a8d.png)

**I'm having that result**

**Comment by sallam-ahmed** [comment]
**Rebuilt and it worked,Binary files weren't updated**
